### ISSUE TITLE
Enable Stopping and then starting back up a process

### ISSUE THREAD

**Issue by ittaiz** [flapdoodle-oss/de.flapdoodle.embed.process#19]
Hi,
I'd like the ability to stop and then start back up a process.
After chatting on twitter with @michaelmosmann he suggested I open an issue here since currently the cleanup is done when stopping the process.
My suggestion is to enable configuring a process to defer this step to system shutdown.
cc @viliusl

**Comment by chef-wong** [comment]
I would also like to note that in the following code, you cannot call the mongoExecutable.start() after mongoExecutable.stop() because of the "stopped" boolean: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/Executable.java#L106

Shouldn't this line be in the stop() method? https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/Executable.java#L77-L88

The "stopped" boolean is always true if you stop thus the MongoExecutable cannot be reused unless rebuilt or context has been reloaded.
